input_perphect:
  bacteria_df: data/perphect-data/all/bacteria_df.csv
  phages_df: data/perphect-data/all/phages_df.csv
  couples_df: data/perphect-data/all-private-oversampled/couples_df.csv
embeddings_dir: data/embeddings
output_dir: output/test/
num_gpu: 0
gpu_id: 0

training_config:
  epochs: 100
  learning_rate: 1e-3
  weight_decay: 1e-4
  batch_size: 256

  training_noise_std: 0.05

  lr_schedule: plateau  # Options: plateau, cosine, none

  reduce_dimensionality: PCA
  n_components_bacteria: 500
  n_components_phages: 500

  stratify_cv: false
  k_folds_cv: 10

  test_split_strategy: random  # Options: random, phage, bacteria
  test_size: 0.2

phages_embedding_models:
  - name: NT2
    params: 
      model_name: nucleotide-transformer-v2-250m-multi-species
    strategy: TopBottomTruncateStrategy
    use_cached_embeddings: true

  - name: MegaDNA
    params: 
      weights_path: data/weights/megaDNA_phage_145M.pt
      get_layer: concat
    strategy: MaxStrategy
    use_cached_embeddings: true

  - name: DNABERT2
    params: 
      source_code_path: DNABERT-2-117M/
      max_seq_len: 32768
    strategy: TKPertStrategy
    use_cached_embeddings: true

bacteria_embedding_models:
  - name: NT2
    params: 
      model_name: nucleotide-transformer-v2-250m-multi-species
    strategy: TopBottomTruncateStrategy
    use_cached_embeddings: true

  - name: MegaDNA
    params: 
      weights_path: data/weights/megaDNA_phage_145M.pt
      get_layer: concat
    strategy: BottomTruncateStrategy
    use_cached_embeddings: true

  - name: DNABERT2
    params: 
      source_code_path: DNABERT-2-117M/
      max_seq_len: 32768
    strategy: TopBottomTruncateStrategy
    use_cached_embeddings: true

classifier: 
  name: BasicMLPClassifier
  params:
    mlp_params: [256, 128]
    dropout: 0.4