input_perphect:
  bacteria_df: data/perphect-data/predphi/bacteria_sequences.csv
  phages_df: data/perphect-data/predphi/bacteriophages_sequences.csv
  couples_df: data/perphect-data/predphi/predphi_train_dataset.csv

embeddings_dir: data/embeddings-pbip
output_dir: output/pbip/test
num_gpu: 0
gpu_id: 0

training_config:
  do_test: true
  epochs: 100
  learning_rate: 1e-3
  batch_size: 256

  training_noise_std: 0.05

  lr_schedule: cosine  # Options: plateau, cosine, none

  stratify_cv: true
  k_folds_cv: 10

  # test_split_strategy: random  # Options: random, phage, bacteria
  test_dataset_path: data/perphect-data/predphi/predphi_test_dataset.csv
  test_size: 0.2

phages_embedding_models:
  - name: NT2
    params: 
      model_name: nucleotide-transformer-v2-250m-multi-species
    strategy: TopBottomTruncateStrategy
    use_cached_embeddings: true

  - name: MegaDNA
    params: 
      weights_path: data/weights/megaDNA_phage_145M.pt
      get_layer: concat
    strategy: TopBottomTruncateStrategy
    use_cached_embeddings: true

  - name: DNABERT2
    params: 
      source_code_path: DNABERT-2-117M/
      max_seq_len: 16384
    strategy: TKPertStrategy
    use_cached_embeddings: true

bacteria_embedding_models:
  - name: NT2
    params: 
      model_name: nucleotide-transformer-v2-250m-multi-species
    strategy: TruncateStrategy
    use_cached_embeddings: true

  - name: MegaDNA
    params: 
      weights_path: data/weights/megaDNA_phage_145M.pt
      get_layer: concat
    strategy: TruncateStrategy
    use_cached_embeddings: true

  - name: DNABERT2
    params: 
      source_code_path: DNABERT-2-117M/
      max_seq_len: 16384
    strategy: BottomTruncateStrategy
    use_cached_embeddings: true


classifier: 
  name: MLPClassifier
  params:
    bacterium_mlp_sizes: [256, 128]
    phage_mlp_sizes: [256, 128]
    dense_dim: 256
    dropout: 0.4
