import yaml
from pydantic import BaseModel, Field, model_validator
from typing import List, Dict, Any, Literal, Tuple, Union
from pbi_models.classifiers.sklearn_classifier import SklearnClassifier
from pbi_utils.embeddings_merging_strategies import *
from pbi_models.embedders import *
from pbi_models.classifiers import *
from pbi_models.classifiers.abstract_classifier import AbstractNNClassifier
from pbi_models.embedders.abstract_model import AbstractModel
from pbi_utils.embeddings_merging_strategies.abstract_merger_strategy import (
    AbstractMergerStrategy,
)
from pbi_utils.logging import Logging
from pbi_utils.types import *
import os
import torch

logger = Logging()


class StrategyConfig(BaseModel):
    """
    Configuration for the merging strategy of embeddings.

    Attributes:
        name (str): Name of the merging strategy to use. Must be a subclass of `AbstractMergerStrategy`, implemented in `pbi_utils.embeddings_merging_strategies`.
        params (Dict[str, Any]): Specific parameters to initialize the merging strategy. They are passed as keyword arguments to the strategy constructor.
    """

    name: str
    params: Dict[str, Any] = Field(default_factory=dict)


class ModelConfig(BaseModel):
    """
    Configuration for an embedding model.

    Attributes:
        name (str): Name of the embedding model to use. Must be a subclass of `AbstractModel`, implemented in `pbi_models.embedders`.
        params (Dict[str, Any]): Specific parameters to initialize the embedding model. They are passed as keyword arguments to the model constructor.
        strategy (StrategyConfig | str): Merging strategy to use when multiple embeddings are generated by this model. If a string, use the default parameters for that strategy.
        use_cached_embeddings (CACHED_EMBEDDINGS_OPTION): If true, do not calculate embeddings for this model, use cached ones from `embeddings_dir`. Also, if true, the embedding models will not be loaded, saving time and possible environment problems. If "auto", use cached embeddings if they exist, otherwise compute them.
    """

    name: str
    params: Dict[str, Any] = Field(default_factory=dict)
    strategy: StrategyConfig | str
    use_cached_embeddings: CACHED_EMBEDDINGS_OPTION = "auto"


class InputConfig(BaseModel):
    """
    Configuration for input data files.

    Attributes:
        bacteria_df (str): Path to the CSV file containing the bacteria sequences.
        phages_df (str): Path to the CSV file containing the phage sequences.
        couples_df (str): Path to the CSV file containing the interaction couples.
    """

    bacteria_df: str
    phages_df: str
    couples_df: str


class ClassifierConfig(BaseModel):
    """
    Configuration for the classifier model.

    Attributes:
        name (str): Name of the classifier model to use. Must be a subclass of `AbstractClassifier`, implemented in `pbi_models.classifiers`.
        params (Dict[str, Any]): Specific parameters to initialize the classifier model. They are passed as keyword arguments to the model constructor.
    """

    name: str
    params: Dict[str, Any] = Field(default_factory=dict)


class TrainingConfig(BaseModel):
    """
    Configuration for the training process.

    Attributes:
        do_train (bool): If false, do not train or test the model, just compute the embeddings.
        do_test (bool): If false, do not test the model after training.
        epochs (int): Number of epochs to train the classifier model.
        batch_size (int): Batch size to use for training and testing of the classifier.
        learning_rate (float): Learning rate to use for training with Adam optimizer.
        weight_decay (float): L2 Regularization for Adam optimizer.
        stratify_cv (bool): Whether to stratify the folds in cross validation. If true, each fold will contain all the interactions for an exclusive subset of all the phages. If false, the folds will be created randomly on the interactions level.
        training_noise_std (float): STD of the noise that is added during training to the embeddings. If 0, do not add noise.
        k_folds_cv (int): Train the classifier model using `k_folds`-Fold cross validation.
        patience_early_stopping (int): Number of epochs to wait without performance increase before the training is interrupted.
        monitor_metric_early_stopping (Literal["f1", "loss"]): The metric to decide wether the model is performing better or not.
        patience_reduce_lr (int): Number of epochs to wait before reducing the learning rate.
        monitor_metric_reduce_lr (Literal["f1", "loss"]): The metric to decide wether the model is performing better or not.
        multiplying_factor_reduce_lr (float): Multiply the learning rate with this after `patience_reduce_lr` epochs without improvement.
        lr_schedule (Literal["plateau", "cosine", "none"]): Learning rate scheduler to use during training.
            ``"plateau"`` uses ReduceLROnPlateau (requires a validation set, i.e. k_folds_cv > 1).
            ``"cosine"`` uses CosineAnnealingLR (works without a validation set).
            ``"none"`` disables LR scheduling entirely.
        reduce_dimensionality (DIMENSIONALITY_REDUCTION_TECHNIQUE): The dimensionality reduction technique to apply to the merged embeddings. If "none", do not use any.
        n_components_bacteria (int | None): If `reduce_dimensionality` is used, only save this number of components. If None, use them all.
        n_components_phages (int | None): If `reduce_dimensionality` is used, only save this number of components. If None, use them all.
        test_split_strategy (Literal["random", "phage", "bacteria", "organism", "predefined"]): Strategy for splitting the dataset into train and test sets when ``do_test=True``.
            ``"random"`` performs a random shuffle split (default behaviour).
            ``"phage"`` holds out ``n_holdout_test`` random phage IDs for testing.
            ``"bacteria"`` holds out ``n_holdout_test`` random bacteria IDs for testing.
            ``"organism"`` holds out ``n_holdout_test`` phages AND all their associated bacteria for testing.
            ``"predefined"`` loads a separate CSV file specified by ``test_dataset_path`` as the test set.
        test_dataset_path (str | None): Path to a separate CSV file to use as the test set. Required when ``test_split_strategy="predefined"``.
        test_size (float): Fraction of the dataset to reserve for testing when ``test_split_strategy="random"``.
        n_holdout_test (int | None): Number of unique phage/bacteria IDs to hold out when ``test_split_strategy`` is ``"phage"``, ``"bacteria"``, or ``"organism"``.
    """

    do_train: bool = True
    do_test: bool = True
    epochs: int = 10
    batch_size: int = 128
    learning_rate: float = 1e-3
    weight_decay: float = 1e-4
    training_noise_std: float = 0.05

    stratify_cv: bool = False
    k_folds_cv: int = 3

    patience_early_stopping: int = 1000
    monitor_metric_early_stopping: Literal["f1", "loss"] = "f1"

    patience_reduce_lr: int = 1000
    monitor_metric_reduce_lr: Literal["f1", "loss"] = "f1"
    multiplying_factor_reduce_lr: float = 0.5

    lr_schedule: Literal["plateau", "cosine", "none"] = "plateau"

    reduce_dimensionality: DIMENSIONALITY_REDUCTION_TECHNIQUE = "none"
    n_components_bacteria: int | None = None
    n_components_phages: int | None = None

    test_split_strategy: Literal["random", "phage", "bacteria", "organism", "predefined"] = "random"
    test_dataset_path: str | None = None
    test_size: float = 0.2
    n_holdout_test: int | None = None


class YAMLConfig(BaseModel):
    """
    Base configuration parsed from the YAML file.

    Attributes:
        input_perphect (str | InputConfig): The path of the folder containing the input data in the Perphect format or an InputConfig object.
        embeddings_dir (str): The path where the embeddings will be stored and read from. Default is "data/embeddings".
        num_gpu (int): Number of GPUs available in the system. Default is 1.
        gpu_id (int): Index of GPU to be employed. Default is 0.
        phages_embedding_models (List[ModelConfig]): Name and parameters of the embedding model to use for the phages sequences.
        bacteria_embedding_models (List[ModelConfig]): Name and parameters of the embedding model to use for the bacteria sequences.
        classifier (ClassifierConfig): Model to use to classify the embeddings. Default is a Linear Classifier with no parameters.
        torch_num_threads (int): Number of threads used by PyTorch. Default is -1, which lets PyTorch decide.
        training_config (TrainingConfig): Configuration for training parameters.
        output_dir (str | None): Output folder. If None, no output folder is used. Default is None.
        seed (int): Base random seed for reproducibility. Each ensemble member i uses seed + i. Default is 42.
        ensemble_size (int): Number of independently-seeded models to train. When > 1, softmax probabilities are averaged at test time. Default is 1 (Single model).
        pca_components (int | str): Shorthand for PCA dimensionality reduction. When set to an integer N, sets both n_components_bacteria and n_components_phages to N and enables PCA. Default is "none".
        calibrate_threshold (bool): When True, performs a post-hoc threshold sweep on a held-out calibration set (split from training data) to maximise F1, then retrains on the full training set. Default is False.
    """

    input_perphect: str | InputConfig
    embeddings_dir: str = "data/embeddings"
    num_gpu: int = 0
    gpu_id: int = 0
    phages_embedding_models: List[ModelConfig] = Field(default_factory=list)
    bacteria_embedding_models: List[ModelConfig] = Field(default_factory=list)
    classifier: ClassifierConfig = Field(
        default_factory=lambda: ClassifierConfig(name="LinearClassifier", params={})
    )
    torch_num_threads: int = -1
    training_config: TrainingConfig = Field(default_factory=TrainingConfig)
    output_dir: str | None = None
    seed: int = 42
    ensemble_size: int = 1
    pca_components: Union[int, str] = "none"
    calibrate_threshold: bool = False


class Config:
    """
    Parsed configuration for the application.
    Attributes:
        input_perphect (InputConfig): Configuration for input data paths.
        embeddings_dir (str): Directory for storing and reading embeddings.
        num_gpu (int): Number of GPUs available.
        gpu_id (int): Index of GPU to be employed.
        training_config (TrainingConfig): Configuration for training parameters.
        phages_embedding_models (List[AbstractModel]): List of instantiated embedding models for phages.
        compute_phages_embeddings (List[CACHED_EMBEDDINGS_OPTION]): List indicating whether to compute embeddings for each phage model.
        bacteria_embedding_models (List[AbstractModel]): List of instantiated embedding models for bacteria.
        compute_bacteria_embeddings (List[CACHED_EMBEDDINGS_OPTION]): List indicating whether to compute embeddings for each bacteria model.
        classifier (Type[AbstractClassifier]): Class of the classifier model to be used.
        classifier_params (Dict[str, Any]): Parameters for initializing the classifier model.
        torch_num_threads (int): Number of threads used by PyTorch.
        output_dir (str | None): Output folder path.
        seed (int): Base random seed. Each ensemble member i uses seed + i.
        ensemble_size (int): Number of independently-seeded models to train (ensemble).
        calibrate_threshold (bool): Whether to perform post-hoc threshold calibration.
    """

    def __init__(self, yaml_config: YAMLConfig, raw_dict):
        self.raw_dict = raw_dict
        if isinstance(yaml_config.input_perphect, str):
            yaml_config.input_perphect = InputConfig(
                bacteria_df=os.path.join(yaml_config.input_perphect, "bacteria_df.csv"),
                phages_df=os.path.join(yaml_config.input_perphect, "phages_df.csv"),
                couples_df=os.path.join(yaml_config.input_perphect, "couples_df.csv"),
            )
        self.input_perphect = yaml_config.input_perphect
        self.embeddings_dir = yaml_config.embeddings_dir
        self.num_gpu = yaml_config.num_gpu
        self.gpu_id = yaml_config.gpu_id
        self.training_config = yaml_config.training_config
        if self.num_gpu == 0:
            self.device = "cpu"
        elif not torch.cuda.is_available():
            logger.warning(
                f"Config requested {self.num_gpu} GPU(s) (gpu_id={self.gpu_id}), but CUDA is not available. Falling back to CPU."
            )
            self.device = "cpu"
        else:
            self.device = f"cuda:{self.gpu_id}"
        logger.debug(f"Config initialized with device: {self.device}")
        self.phages_embedding_models, self.compute_phages_embeddings = (
            self._parse_models(yaml_config.phages_embedding_models)
        )
        self.bacteria_embedding_models, self.compute_bacteria_embeddings = (
            self._parse_models(yaml_config.bacteria_embedding_models)
        )
        self.classifier = self._get_instance_from_string(
            yaml_config.classifier.name,
            subclass_of=(AbstractNNClassifier, SklearnClassifier),
        )  # The classifier is not instantiated yet because we need to know the embedding dimensions first, and that is only known after loading them (in main.py)
        self.classifier_params = yaml_config.classifier.params
        self.torch_num_threads = yaml_config.torch_num_threads
        self.output_dir = yaml_config.output_dir

        self.seed = yaml_config.seed
        self.ensemble_size = yaml_config.ensemble_size
        self.calibrate_threshold = yaml_config.calibrate_threshold

        # When pca_components set to an integer, override both PCA component counts and enable PCA dimensionality reduction.
        if yaml_config.pca_components != "none":
            n = int(yaml_config.pca_components)
            self.training_config.n_components_bacteria = n
            self.training_config.n_components_phages = n
            self.training_config.reduce_dimensionality = "PCA"

        tc = self.training_config
        if tc.test_split_strategy == "predefined" and tc.test_dataset_path is None:
            raise ValueError(
                "test_split_strategy='predefined' requires test_dataset_path to be set."
            )

        # Too many combinations
        if self.ensemble_size > 1 and tc.k_folds_cv > 1:
            logger.warning(
                f"ensemble_size={self.ensemble_size} with k_folds_cv={tc.k_folds_cv} "
                f"will train {self.ensemble_size * tc.k_folds_cv} models total. "
                "Each fold trains the full ensemble and evaluates it as one unit."
            )

    def _parse_models(
        self, models_config: List[ModelConfig]
    ) -> Tuple[List[AbstractModel], List[CACHED_EMBEDDINGS_OPTION]]:
        models = []
        cached_embeddings = []
        for model_config in models_config:
            if isinstance(model_config.strategy, str):
                merging_strategy = self._get_instance_from_string(
                    model_config.strategy, subclass_of=AbstractMergerStrategy
                )()
            else:
                merging_strategy = self._get_instance_from_string(
                    model_config.strategy.name, subclass_of=AbstractMergerStrategy
                )(**model_config.strategy.params)

            model_params = model_config.params
            model_params["merging_strategy"] = merging_strategy
            model_params["device"] = self.device
            model_params["load_model"] = model_config.use_cached_embeddings != True

            model = self._get_instance_from_string(
                model_config.name, subclass_of=AbstractModel
            )(**model_params)
            models.append(model)
            cached_embeddings.append(model_config.use_cached_embeddings)
        return models, cached_embeddings

    def _get_instance_from_string(self, class_name: str, subclass_of: type | tuple):
        if class_name in globals() and issubclass(globals()[class_name], subclass_of):
            model_class = globals()[class_name]
            return model_class
        else:
            raise ValueError(f"Class {class_name} not found or is not a subclass of {(x.__name__ for x in subclass_of) if type(subclass_of) is tuple else subclass_of.__name__}.")  # type: ignore

    def __repr__(self):
        return (
            f"Config(input_perphect={self.input_perphect}, embeddings_dir={self.embeddings_dir}, "
            f"num_gpu={self.num_gpu}, gpu_id={self.gpu_id}, "
            f"seed={self.seed}, ensemble_size={self.ensemble_size}, "
            f"calibrate_threshold={self.calibrate_threshold}, "
            f"training_config=TrainingConfig({self.training_config}), "
            f"phages_embedding_models={self.phages_embedding_models}, "
            f"compute_phages_embeddings={self.compute_phages_embeddings}, "
            f"bacteria_embedding_models={self.bacteria_embedding_models}, "
            f"compute_bacteria_embeddings={self.compute_bacteria_embeddings}, "
            f"torch_num_threads={self.torch_num_threads}, "
            f"output_dir={self.output_dir}, "
            f"classifier={self.classifier.__name__}({self.classifier_params})"
            f")"
        )


def parse_config(config_path: str | None = None, json_cli: str | None = None) -> Config:
    """
    Parse configuration from a YAML file or a JSON string.

    :param config_path: Path to the YAML configuration file. If None, `json_cli` must be provided.
    :type config_path: str | None
    :param json_cli: JSON string containing the configuration. If None, `config_path` must be provided.
    :type json_cli: str | None
    :return: Parsed configuration object
    :rtype: Config
    """
    if config_path is not None:
        with open(config_path, "r") as f:
            config_dict = yaml.safe_load(
                os.path.expandvars(f.read())
            )  # Read file replacing env vars with their value

    elif json_cli is not None:
        config_dict = yaml.safe_load(json_cli)

    else:
        raise ValueError("Either config_path or json_cli must have a value.")

    yaml_config = YAMLConfig(**config_dict)

    c = Config(yaml_config, config_dict)

    logger.info(f"Configuration loaded from {config_path}: {c}")

    return c
